#!/bin/bash
sudo su

yum update -y
yum install httpd php php-mysql -y

cd /var/www/html
wget https://wordpress.org/wordpress-5.1.1.tar.gz
tar -xvf wordpress-5.1.1.tar.gz

cp -r wordpress/* /var/www/html/
rm -rf wordpress wordpress-5.1.1.tar.gz

chmod -R 755 wp-content
chown apache:apache -R wp-content
chkconfig httpd on
service httpd start
